version: "2"
services:
  frontend:
    build:
     context: ./React
     dockerfile: Dockerfile
    environment:
     - DEPENDS_ON=backend:8443
    expose:
     - "3000"
    ports:
      - "80:3000"
    depends_on:
      - backend
  backend:
    build:
     context: ./java_spring
     dockerfile: Dockerfile
    environment:
     - DEPENDS_ON=db:3306
    expose:
     - "8443"
    ports:
     - "8443:8443"
    depends_on:
     - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
     - MYSQL_ROOT_PASSWORD=root
    expose:
     - "3306"
    ports:
     - "3306:3306"
