spring:
  application:
    name: art-biz
    description: Artwork selling platform

---
#Active environment
spring:
  profiles:
    active: dev

---
#Dev settings
spring:
  profiles: dev

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:file:./devDb
    username:
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8080


---
#Prod settings
spring:
  profiles: prod

server:
  port: 8443

  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: 123456
    key-store-type: JKS
    key-alias: artBizSsl